# Change these first
owner: cloudwan # Your GitHub organization or username, where this repository lives
repo: edgelq-statuspage # The name of this repository

sites:
  - name: EdgeLQ API
    url: http://healthcheck.europe-west3.unagi.dev02.nttclouds.co/edgelq_api_healthcheck
    method: GET
  - name: STG Smoke Tests
    url: https://api.github.com/repos/cloudwan/qa/actions/workflows/25360914/runs?per_page=1&page=1&status=completed
    method: GET
    headers:
      - "Accept: application/vnd.github+json"
      - "Authorization: Bearer $GH_PAT"
    __dangerous__body_down_if_text_missing: '"conclusion": "success"'



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: wwwwwupptime.js.org
  # baseUrl: /edgelq-statuspage
  cname: status.edgelq.com
  logoUrl: https://raw.githubusercontent.com/AlexBula/test_status/master/assets/ntt.png
  apiBaseUrl: https://api.github.com
  name: Edgelq Status Page
  introTitle: "**About this site**."
  introMessage: '''The status page of the Edgelq Systems. It shows the current status of the systems and backend services.


  Currently you can see status of:
    * EdgeLQ API - runs a healthcheck on all our backend services to spot any problem with the API availbility for the external user. Hence it checks a number of services, it requires all of them to be healthy.
    * STG Smoke Tests - checks the status of the most recent Smoke Test run - smoke tests are run in the background and verify that all our essential API endpoints work as expected.


    If any check causes some problem (is down, unhealthy etc), or a downtime is scheduled by the EdgeLQ Team, it will be displayed on the top of the page. If situation happened, anyone interested with the updates in regards to that matter will be able to subscribe to the github issue created and releated to the incident/maintenance.'''
  css: "article > div:nth-child(3) {
          visibility: hidden;
          font-size: 0;
          padding: 0;
          margin: 0;
  }"


workflowSchedule:
  uptime: "*/30 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
